dist: trusty
sudo: true

language: python
python:
  - 3.6
  - 3.7

install:
  - pip install tox
  - pip install coveralls
  #- pip install python-coveralls

env:
  - DJANGO=django21
  - DJANGO=django22 # long-term support release

script:
  - tox -e $DJANGO-py${TRAVIS_PYTHON_VERSION//[.]/}

after_success:
  - coveralls
