dist: xenial
sudo: true

language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install tox
  - pip install coveralls
  - sudo apt-get install gdal-bin libgdal-dev
  #- pip install python-coveralls

env:
  - DJANGO=django111
  - DJANGO=django11117
  - DJANGO=django20
  - DJANGO=django21
  - DJANGO=django22
  - DJANGO=django228
  - DJANGO=django30

# Workaround for Travis issues with unknown python interpreters
matrix:
  exclude:
    - python: 2.7
      env: DJANGO=django20
    - python: 2.7
      env: DJANGO=django21
    - python: 2.7
      env: DJANGO=django22
    - python: 2.7
      env: DJANGO=django228
    - python: 2.7
      env: DJANGO=django30
    - python: 3.4
      env: DJANGO=django21
    - python: 3.4
      env: DJANGO=django22
    - python: 3.4
      env: DJANGO=django228
    - python: 3.4
      env: DJANGO=django30
    - python: 3.5
      env: DJANGO=django30
    - python: 3.7
      env: DJANGO=django111
    - python: 3.8
      env: DJANGO=django111
    - python: 3.8
      env: DJANGO=django11117
    - python: 3.8
      env: DJANGO=django20
    - python: 3.8
      env: DJANGO=django21
    - python: 3.8
      env: DJANGO=django22

script:
  - tox -e $DJANGO-py${TRAVIS_PYTHON_VERSION//[.]/}

after_success:
  - coveralls
